name: Python CI

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks out your repository so the workflow can access the code
    - name: Checkout code
      uses: actions/checkout@v4

    # Sets up Python with a specific version (e.g., 3.10)
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # Upgrade pip and install dependencies from requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Lint the code using flake8
    - name: Lint with flake8
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit with 0 if no issues, otherwise exit with 1
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    # Test the code using pytest
    - name: Test with pytest
      run: |
        pytest   